### PR TITLE
Fix a somewhat huge bug

### PR DESCRIPTION
**Pull request by saitohirga**
As of now you can use a bow and kill your self and get PerkPoints. My code fixes that and you get a nice little message saying "No PerkPoints for you :(". Shaming the user for trying. (Feel free to change or remove it)

### CODE REVIEW

**Comment by HmmmQuestionMark** [comment]
Please clean up the code to fit the style used everywhere else (use brackets {} and appropriate tabs and spacing).

Also, the message is nice, it is a bit unnecessary. If you want to have this PR pulled, then please fix those issues. Thanks for taking the initiative!

**Comment by saitohirga** [comment]
Okay I fixed the ones you wanted me to. Ready to hear back.

**Comment by HmmmQuestionMark** [comment]
Ah, that wasn't what I had in mind. I meant only for your changes, not for the entire file.

**Comment by HmmmQuestionMark** [comment]
If you could revert your changes to the previous and then change only the new code you added, that'd be great.

**Comment by saitohirga** [comment]
I am done with the changes. Tell me how it looks.

**Comment by janie177** [comment]
I'm pretty sure this is possible only once a day though.

**Comment by HmmmQuestionMark** [comment]
I'm sorry, but you haven't fixed what needs fixed...

**Pull request closed without merging**
